server:
  servlet:
    context-path: /
  address: 0.0.0.0
  port: 8080
  tomcat:
    redirect-context-root: false
spring:
  data:
    mongodb:
      uri: mongodb://scrolls:BALNkBD28x@172.16.40.1:27701,172.16.40.2:27701,172.16.40.3:27701/scrolls
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 20000000